In [5]:
from caveclient import CAVEclient
from intern import array
import pickle
import numpy as np
from agents import data_loader
from cloudvolume import CloudVolume
from membrane_detection import membranes
from agents.scripts import precompute_membrane_vectors, create_post_matrix, merge_paths, get_soma
import agents.sensor
from agents.run import run_agents
import aws.sqs as sqs
import sys
import time
import ast
import pandas as pd
import agents.scripts as scripts
from drive import drive
from finding_orphans import *
from math import sqrt
from tip_finding.tip_finding import tip_finder_decimation

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
load = pd.read_csv("agents/Data/endpoints_gt4.csv")
endpoints_dict = {}

In [7]:
load.head()

neuron                                            ng_link  \
0  8.646911e+17  https://neuroglancer.neuvue.io/?json_url=https...   
1           NaN                                                NaN   
2           NaN                                                NaN   
3           NaN                                                NaN   
4           NaN                                                NaN   

               seg_id                 pink_pts  num_endpoints  \
0  864691135909994000  (402188, 228684, 24029)              2   
1  864691135247440303  (401258, 224832, 24029)              3   
2  864691134794123793  (401314, 228366, 24424)              2   
3  864691134959738482  (400199, 220721, 24029)              7   
4  864691135314714227  (397870, 232292, 24004)              2   

                                           endpoints comments  \
0  ((402584, 228856, 23991), (402985, 229235, 235...      NaN   
1  ((401612, 224623, 23991), (405257, 226318, 236...      NaN   
2  ((401242, 228382, 24444), (400982, 228457, 245...      NaN   
3  ((401289, 218721, 23991), (399895, 216533, 235...      NaN   
4  ((397867, 232230, 23999), (397854, 232252, 239...      NaN   

  detailed_comments  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN

In [8]:
#creating series objects for the desired collumns 
segIDs = load['seg_id']
Endpoints = load['endpoints']



In [9]:
for idx, i in enumerate(load['seg_id']):
    #if idx==10:
        #break
    try:
        t1, skel, mesh_obj = tip_finder_decimation(str(i))
        endpoints_dict[i] = t1
    except:
        print(f"\n\nSeg {i} returned error on get. Skipping.\n")
        pass

load['endpoints'] = load['endpoints'].apply(lambda x: list(ast.literal_eval(x)))
load['proposed_endpoints'] = load.seg_id.map(endpoints_dict)

07/22/2022 03:49:57 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3996/3996 [00:00<00:00, 558811.68it/s]
07/22/2022 03:50:02 PM WARNING: face_normals incorrect shape, ignoring! 


  0%|          | 0/10649 [00:00<?, ?it/s]/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/meshparty/skeletonize.py:613: RuntimeWarning: invalid value encountered in multiply
  target = np.nanargmax(root_ds * valid)
100%|██████████| 10649/10649 [00:00<00:00, 444876.38it/s]
07/22/2022 03:50:04 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1140/1140 [00:00<00:00, 405831.49it/s]
07/22/2022 03:50:06 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2596/2596 [00:00<00:00, 527130.77it/s]
07/22/2022 03:50:07 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 117/117 [00:00<00:00, 48453.16it/s]
07/22/2022 03:50:08 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 725/725 [00:00<00:00, 315344.85it/s]
07/22/2022 03:50:10 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3024/3024 [00:00<00:00, 536076.72it/s]
07/22/2022 03:50:11 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 590/590 [00:00<00:00, 202673.17it/s]
07/22/2022 03:50:13 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3024/3024 [00:00<00:00, 514818.17it/s]
07/22/2022 03:50:15 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 33205/33205 [00:00<00:00, 150900.89it/s]
07/22/2022 03:50:19 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 338/338 [00:00<00:00, 184617.11it/s]
07/22/2022 03:50:21 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5856/5856 [00:00<00:00, 425859.01it/s]
07/22/2022 03:50:22 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 7270/7270 [00:00<00:00, 574616.33it/s]
07/22/2022 03:50:24 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 12420/12420 [00:00<00:00, 557970.65it/s]
07/22/2022 03:50:27 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 11545/11545 [00:00<00:00, 726203.35it/s]
07/22/2022 03:50:29 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133692934758 returned error on get. Skipping.



07/22/2022 03:50:30 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 158/158 [00:00<00:00, 84852.76it/s]
07/22/2022 03:50:31 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1243/1243 [00:00<00:00, 343175.35it/s]
07/22/2022 03:50:32 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133946526057 returned error on get. Skipping.



07/22/2022 03:50:33 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133712131152 returned error on get. Skipping.



07/22/2022 03:50:34 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 204/204 [00:00<00:00, 105908.90it/s]
07/22/2022 03:50:37 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 22603/22603 [00:00<00:00, 421232.51it/s]
07/22/2022 03:50:41 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3568/3568 [00:00<00:00, 540048.24it/s]
07/22/2022 03:50:42 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133678427777 returned error on get. Skipping.



07/22/2022 03:50:43 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 556/556 [00:00<00:00, 236682.54it/s]
07/22/2022 03:50:44 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1119/1119 [00:00<00:00, 404292.03it/s]
07/22/2022 03:50:45 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3576/3576 [00:00<00:00, 580135.81it/s]
07/22/2022 03:50:47 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 230/230 [00:00<00:00, 130681.38it/s]
07/22/2022 03:50:48 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1402/1402 [00:00<00:00, 390439.83it/s]
07/22/2022 03:50:49 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133766052845 returned error on get. Skipping.



07/22/2022 03:50:50 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1499/1499 [00:00<00:00, 181032.59it/s]
07/22/2022 03:50:53 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 14992/14992 [00:00<00:00, 726486.11it/s]
07/22/2022 03:50:55 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 351/351 [00:00<00:00, 177995.49it/s]
07/22/2022 03:50:56 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3586/3586 [00:00<00:00, 511330.07it/s]
07/22/2022 03:50:58 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5274/5274 [00:00<00:00, 701889.81it/s]
07/22/2022 03:50:59 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 7026/7026 [00:00<00:00, 694340.04it/s]
07/22/2022 03:51:01 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2368/2368 [00:00<00:00, 521015.15it/s]
07/22/2022 03:51:03 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 4525/4525 [00:00<00:00, 531169.73it/s]
07/22/2022 03:51:05 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 15505/15505 [00:00<00:00, 714354.42it/s]
07/22/2022 03:51:10 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 28900/28900 [00:00<00:00, 345416.79it/s]
07/22/2022 03:51:14 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 6582/6582 [00:00<00:00, 555772.93it/s]
07/22/2022 03:51:19 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 105180/105180 [00:00<00:00, 245867.66it/s]
07/22/2022 03:51:31 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 18513/18513 [00:00<00:00, 481294.40it/s]
07/22/2022 03:51:36 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 15061/15061 [00:00<00:00, 321226.18it/s]
07/22/2022 03:51:41 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 14865/14865 [00:00<00:00, 655373.78it/s]
07/22/2022 03:51:49 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 73820/73820 [00:01<00:00, 52492.62it/s] 
07/22/2022 03:52:05 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5791/5791 [00:00<00:00, 498455.02it/s]
07/22/2022 03:52:08 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 14714/14714 [00:00<00:00, 285410.99it/s]
07/22/2022 03:52:11 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 12530/12530 [00:00<00:00, 449284.71it/s]
07/22/2022 03:52:15 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 26058/26058 [00:00<00:00, 639927.71it/s]
07/22/2022 03:52:26 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 210150/210150 [00:01<00:00, 116190.15it/s]
07/22/2022 03:52:52 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3699/3699 [00:00<00:00, 408239.41it/s]
07/22/2022 03:52:54 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 8352/8352 [00:00<00:00, 541744.54it/s]
07/22/2022 03:52:57 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 17575/17575 [00:00<00:00, 679518.93it/s]
07/22/2022 03:53:01 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 17800/17800 [00:00<00:00, 339331.10it/s]
07/22/2022 03:53:03 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1644/1644 [00:00<00:00, 423136.71it/s]
07/22/2022 03:53:05 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 11380/11380 [00:00<00:00, 514793.94it/s]
07/22/2022 03:53:07 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 152/152 [00:00<00:00, 54401.76it/s]
07/22/2022 03:53:09 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 934/934 [00:00<00:00, 379821.60it/s]
07/22/2022 03:53:12 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 73645/73645 [00:00<00:00, 304658.12it/s]
07/22/2022 03:53:21 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 403/403 [00:00<00:00, 213449.24it/s]
07/22/2022 03:53:22 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5928/5928 [00:00<00:00, 450872.85it/s]
07/22/2022 03:53:25 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 8016/8016 [00:00<00:00, 740578.89it/s]
07/22/2022 03:53:26 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 264/264 [00:00<00:00, 88181.59it/s]
07/22/2022 03:53:29 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 30530/30530 [00:00<00:00, 552627.59it/s]
07/22/2022 03:53:34 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 3806/3806 [00:00<00:00, 568643.22it/s]
07/22/2022 03:53:35 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 7820/7820 [00:00<00:00, 719081.34it/s]
07/22/2022 03:53:37 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133769133345 returned error on get. Skipping.



07/22/2022 03:53:41 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 49920/49920 [00:00<00:00, 333066.07it/s]
07/22/2022 03:53:48 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 43892/43892 [00:00<00:00, 524873.96it/s]
07/22/2022 03:53:55 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 19407/19407 [00:00<00:00, 456279.30it/s]
07/22/2022 03:53:58 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2448/2448 [00:00<00:00, 408337.89it/s]
07/22/2022 03:54:01 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 39637/39637 [00:00<00:00, 225692.52it/s]
07/22/2022 03:54:07 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 8835/8835 [00:00<00:00, 596274.57it/s]
07/22/2022 03:54:09 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 9474/9474 [00:00<00:00, 701296.04it/s]
07/22/2022 03:54:12 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 19620/19620 [00:00<00:00, 656850.85it/s]
07/22/2022 03:54:16 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1286/1286 [00:00<00:00, 397368.13it/s]
07/22/2022 03:54:18 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 23442/23442 [00:00<00:00, 596949.01it/s]
07/22/2022 03:54:23 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 36158/36158 [00:00<00:00, 447909.40it/s]
07/22/2022 03:54:29 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 4826/4826 [00:00<00:00, 562207.29it/s]
07/22/2022 03:54:30 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1973/1973 [00:00<00:00, 512247.71it/s]
07/22/2022 03:54:44 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 187763/187763 [00:06<00:00, 27341.48it/s]
07/22/2022 03:55:17 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 485/485 [00:00<00:00, 215058.40it/s]
07/22/2022 03:55:21 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 37232/37232 [00:00<00:00, 244717.14it/s]
07/22/2022 03:55:26 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2640/2640 [00:00<00:00, 383558.92it/s]
07/22/2022 03:55:28 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5980/5980 [00:00<00:00, 475243.72it/s]
07/22/2022 03:55:30 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 7616/7616 [00:00<00:00, 509535.81it/s]
07/22/2022 03:55:31 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1211/1211 [00:00<00:00, 418876.97it/s]
07/22/2022 03:55:33 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1359/1359 [00:00<00:00, 399611.55it/s]
07/22/2022 03:55:34 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 11308/11308 [00:00<00:00, 593599.45it/s]
07/22/2022 03:55:37 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 191/191 [00:00<00:00, 111513.37it/s]
07/22/2022 03:55:38 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 105/105 [00:00<00:00, 53195.06it/s]
07/22/2022 03:55:39 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 7685/7685 [00:00<00:00, 356199.73it/s]
07/22/2022 03:55:42 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 6048/6048 [00:00<00:00, 606376.41it/s]
07/22/2022 03:55:44 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 6896/6896 [00:00<00:00, 505645.26it/s]
07/22/2022 03:55:45 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2858/2858 [00:00<00:00, 575732.23it/s]
07/22/2022 03:55:47 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 4775/4775 [00:00<00:00, 437948.04it/s]
07/22/2022 03:55:48 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1010/1010 [00:00<00:00, 286620.23it/s]
07/22/2022 03:55:50 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 8895/8895 [00:00<00:00, 561230.13it/s]
07/22/2022 03:55:52 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691132747855184 returned error on get. Skipping.



07/22/2022 03:55:58 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 126419/126419 [00:00<00:00, 263504.58it/s]
07/22/2022 03:56:13 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 22194/22194 [00:00<00:00, 357317.61it/s]
07/22/2022 03:56:18 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 33346/33346 [00:00<00:00, 436328.21it/s]
07/22/2022 03:56:23 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 22364/22364 [00:00<00:00, 462465.50it/s]
07/22/2022 03:56:26 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 152/152 [00:00<00:00, 91665.59it/s]
07/22/2022 03:56:27 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 5763/5763 [00:00<00:00, 714908.58it/s]
07/22/2022 03:56:29 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691136347887475 returned error on get. Skipping.



07/22/2022 03:56:30 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1905/1905 [00:00<00:00, 447702.65it/s]
07/22/2022 03:56:31 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 138/138 [00:00<00:00, 77693.15it/s]
07/22/2022 03:56:33 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 11909/11909 [00:00<00:00, 553652.41it/s]
07/22/2022 03:56:35 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691133525367772 returned error on get. Skipping.



07/22/2022 03:56:41 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 120275/120275 [00:00<00:00, 212468.05it/s]
07/22/2022 03:57:00 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 202161/202161 [00:01<00:00, 174448.46it/s]
07/22/2022 03:57:22 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 194/194 [00:00<00:00, 104749.61it/s]
07/22/2022 03:57:24 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 128/128 [00:00<00:00, 58693.66it/s]
07/22/2022 03:57:25 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 266/266 [00:00<00:00, 135365.79it/s]
07/22/2022 03:57:26 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1532/1532 [00:00<00:00, 459633.31it/s]
07/22/2022 03:57:28 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2876/2876 [00:00<00:00, 549784.34it/s]
07/22/2022 03:57:30 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 4484/4484 [00:00<00:00, 399491.46it/s]
07/22/2022 03:57:32 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 13121/13121 [00:00<00:00, 512917.31it/s]
07/22/2022 03:57:34 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 1758/1758 [00:00<00:00, 461166.20it/s]
07/22/2022 03:57:35 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691132647441812 returned error on get. Skipping.



07/22/2022 03:57:37 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 20125/20125 [00:00<00:00, 366208.68it/s]
07/22/2022 03:57:42 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 11410/11410 [00:00<00:00, 800137.24it/s]
07/22/2022 03:57:45 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 15601/15601 [00:00<00:00, 637373.73it/s]
07/22/2022 03:57:48 PM WARNING: face_normals incorrect shape, ignoring! 




Seg 864691136597387729 returned error on get. Skipping.



07/22/2022 03:57:50 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 13348/13348 [00:00<00:00, 535286.07it/s]
07/22/2022 03:57:53 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 2543/2543 [00:00<00:00, 475592.59it/s]
07/22/2022 03:57:56 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 13258/13258 [00:00<00:00, 548284.22it/s]
07/22/2022 03:57:59 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 9618/9618 [00:00<00:00, 718498.48it/s]
07/22/2022 03:58:04 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 38734/38734 [00:00<00:00, 194500.49it/s]
07/22/2022 03:58:09 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 811/811 [00:00<00:00, 277816.12it/s]
07/22/2022 03:58:10 PM WARNING: face_normals incorrect shape, ignoring! 


100%|██████████| 9313/9313 [00:00<00:00, 438814.97it/s]


In [11]:
#correctly  have 2 collumns for the proposed vs gt endpoints
load.head(15)

neuron                                            ng_link  \
0   8.646911e+17  https://neuroglancer.neuvue.io/?json_url=https...   
1            NaN                                                NaN   
2            NaN                                                NaN   
3            NaN                                                NaN   
4            NaN                                                NaN   
5            NaN                                                NaN   
6   8.646911e+17  https://neuroglancer.neuvue.io/?json_url=https...   
7            NaN                                                NaN   
8            NaN                                                NaN   
9            NaN                                                NaN   
10           NaN                                                NaN   
11           NaN                                                NaN   
12           NaN                                                NaN   
13           NaN                                                NaN   
14           NaN                                                NaN   

                seg_id                 pink_pts  num_endpoints  \
0   864691135909994000  (402188, 228684, 24029)              2   
1   864691135247440303  (401258, 224832, 24029)              3   
2   864691134794123793  (401314, 228366, 24424)              2   
3   864691134959738482  (400199, 220721, 24029)              7   
4   864691135314714227  (397870, 232292, 24004)              2   
5   864691135552841025  (403272, 227529, 24394)              2   
6   864691135516937065   (77233, 113188, 20454)              2   
7   864691134406233920  (100382, 143836, 21642)              2   
8   864691135516937065   (77233, 113188, 20454)              2   
9   864691136080776044   (80699, 146603, 20732)              5   
10  864691134330810585   (72020, 146120, 20454)              2   
11  864691135337564242   (78888, 144940, 20729)              5   
12  864691135920135864   (77581, 107903, 21128)              2   
13  864691135730780609   (79752, 135765, 21128)              3   
14  864691135651129491   (81247, 106776, 21128)              2   

                                            endpoints comments  \
0   [(402584, 228856, 23991), (402985, 229235, 235...      NaN   
1   [(401612, 224623, 23991), (405257, 226318, 236...      NaN   
2   [(401242, 228382, 24444), (400982, 228457, 245...      NaN   
3   [(401289, 218721, 23991), (399895, 216533, 235...      NaN   
4   [(397867, 232230, 23999), (397854, 232252, 239...      NaN   
5   [(403332, 227545, 24398), (403566, 227614, 244...      NaN   
6    [(77262, 113088, 20442), (79178, 109116, 20402)]      NaN   
7   [(100475, 143982, 21654), (100583, 144194, 217...      NaN   
8    [(77262, 113088, 20442), (79178, 109116, 20402)]        d   
9   [(80890, 147158, 20708), (81592, 148549, 20453...       mm   
10   [(71898, 146194, 20442), (71499, 146291, 20404)]      NaN   
11  [(78610, 145071, 20707), (75884, 143590, 20453...      NaN   
12    [(77575, 107807, 21133), (77000, 99565, 21215)]      NaN   
13  [(79785, 135709, 21133), (84176, 127514, 21582...      NaN   
14    [(81198, 106660, 21133), (88864, 99498, 20482)]      NaN   

                  detailed_comments  \
0                               NaN   
1                               NaN   
2                               NaN   
3                               NaN   
4                               NaN   
5                               NaN   
6                               NaN   
7                               NaN   
8   same point as previous endpoint   
9                               NaN   
10                              NaN   
11                              NaN   
12                              NaN   
13                              NaN   
14                              NaN   

                                   proposed_endpoints  
0   [(402567, 228758, 23991), (402990, 229222, 235...  
1   [(401467, 224644, 

In [12]:

def find_euclidian_distance(proposed_endpoint, gt_endponts_array):
    smallest_distance = 2**30
    for endpoint in gt_endponts_array:
        difference = proposed_endpoint - endpoint
        distance = np.sqrt(np.sum(np.square(difference)))
        if(distance < smallest_distance):
            smallest_distance = distance 
    return smallest_distance 
            
    #could add endpoint to dict
    
     


In [2]:
def get_recall(num_correct, array_endpoints): 
    recall = num_correct / len(array_endpoints)
    return recall * 100

In [13]:
def get_precision(num_correct, array_proposed): 
    precision = num_correct / len(array_proposed)
    return precision * 100

In [14]:
#TEST 1: invalidation_d at default: 12000, WITH Humfrey_Smoothing: 50 iterations, Decimation_Factor = 0.50

#should track total amount of correct gt recovered 

for index, row in load.iterrows():
    #reset num correct
    num_correct = 0
    threshold = 500
    endpoint_array = np.array(row["endpoints"])
    proposed_endpoints_array = np.array(row["proposed_endpoints"])
    print(f"Seg id: %i" %(row["seg_id"]))
    print("Endpoint Array:")
    print(endpoint_array)
    #print(len(endpoint_array))
    print()
    print("Proposed Endpoint Array:")
    print(proposed_endpoints_array)
    print()
    #print(load["Endpoints"])

    #skip sharply angled/false merged
    if row["comments"] == 'a':
        print("skipping")
        print()
        continue

    #skip small seg ids
    if row["comments"] == 's':
        print("skipping")
        print()
        continue 
   
    #skip any seg ids with false merges: 
    if row["comments"] in ('m', "mm", "e"):
        print("skipping")
        print()
        continue

    #learn better pandas filtered rather than if else statements 

    #maybe skip v-shaped segments

    #add in a label for ground truth 
    
    #if both say no endpoints, then it's correct
    if (len(proposed_endpoints_array.shape) == 0 and len(endpoint_array.shape) == 0):
        print("correct, no endpoints")
        print("\nNEXT POINTS")
        continue
    #if we propose no endpoints but there are endpoints, it's wrong
    elif (len(proposed_endpoints_array.shape) == 0 and len(endpoint_array.shape) > 0):
        print("no proposed endpoints found, but ground truth endpoints exist")
        print("\nNEXT POINTS")
        continue 

    #if we propose endpoints but there are none, it's wrong
    elif proposed_endpoints_array.size > 0 and endpoint_array.size == 0:
        print("not correct--too many proposed endpoints but none ground truth endpoints exist")
        print("\nNEXT POINTS")
        continue
    #should skip for now if the endpoint array is size zero to avoid divide by zero error
    elif endpoint_array.size == 0:
        print("array size is 0")
        print("\nNEXT POINTS")
        continue
    else:                                                                                   
        for proposed_endpoint in proposed_endpoints_array:
            smallest_distance= find_euclidian_distance(proposed_endpoint, endpoint_array)
            print(smallest_distance)
            
            
            #compare to threshold and return yes or no 
            if smallest_distance < threshold:
                print("correct")
                num_correct = num_correct + 1
                print()
            else:
                print("wrong")
                print()
        #get precision and recall at end of each iteration 
        recall = get_recall(num_correct, endpoint_array)
        precision = get_precision(num_correct, proposed_endpoints_array)
        print("recall = " + str(recall))
        print("precision = " + str(precision))
        if recall > 100.0 or precision > 100.0:
            print("ERROR: RESULTS OVER 100% DETECTED")
        print()
        print("\nNEXT POINTS")
        
        
    

Seg id: 864691135909994000
Endpoint Array:
[[402584 228856  23991]
 [402985 229235  23554]]

Proposed Endpoint Array:
[[402567 228758  23991]
 [402990 229222  23552]]

99.46356116689167
correct

14.071247279470288
correct

recall = 100.0
precision = 100.0


NEXT POINTS
Seg id: 864691135247440303
Endpoint Array:
[[401612 224623  23991]
 [405257 226318  23620]
 [409162 219642  23891]]

Proposed Endpoint Array:
[[401467 224644  23990]
 [405021 226754  23620]
 [409143 219355  23868]]

146.5162107072115
correct

495.77414212522217
correct

288.54635676091976
correct

recall = 100.0
precision = 100.0


NEXT POINTS
Seg id: 864691134794123793
Endpoint Array:
[[401242 228382  24444]
 [400982 228457  24513]]

Proposed Endpoint Array:
[[400269 228563  24514]
 [400319 228912  24514]]

720.8370134780816
wrong

804.1113107026912
wrong

recall = 0.0
precision = 0.0


NEXT POINTS
Seg id: 864691134959738482
Endpoint Array:
[[401289 218721  23991]
 [399895 216533  23526]
 [406366 215719  23621]
 [403940

In [75]:
load.head()

neuron                                            ng_link  \
0  8.646911e+17  https://neuroglancer.neuvue.io/?json_url=https...   
1           NaN                                                NaN   
2           NaN                                                NaN   
3           NaN                                                NaN   
4           NaN                                                NaN   

               seg_id                 pink_pts  num_endpoints  \
0  864691135909994000  (402188, 228684, 24029)              2   
1  864691135247440303  (401258, 224832, 24029)              3   
2  864691134794123793  (401314, 228366, 24424)              2   
3  864691134959738482  (400199, 220721, 24029)              7   
4  864691135314714227  (397870, 232292, 24004)              2   

                                           Endpoints Comments  \
0  [(402584, 228856, 23991), (402985, 229235, 235...      NaN   
1  [(401612, 224623, 23991), (405257, 226318, 236...      NaN   
2  [(401242, 228382, 24444), (400982, 228457, 245...      NaN   
3  [(401289, 218721, 23991), (399895, 216533, 235...      NaN   
4  [(397867, 232230, 23999), (397854, 232252, 239...      NaN   

                                  proposed_endpoints  
0  [(402567, 228758, 23991), (402990, 229222, 235...  
1  [(401467, 224644, 23990), (405021, 226754, 236...  
2  [(400269, 228563, 24514), (400319, 228912, 245...  
3  [(400448, 220975, 24009), (401240, 217916, 240...  
4  [(397815, 232393, 23996), (397931, 232013, 240...

make threshold for each endpoint
experiment with box (cannot overlap)
for each endpoint see if it finds in box -- if yes true found endpont, if false --not an endpoint
find distance from predicted to ground truth 
could still do MSE 

Threshold: 
-find the size of the segment (maybe connected componenets)
-array from the skel
-flat is edge case 
-maybe a percentage 
--a hard number 





In [33]:
if len(proposed_endpoints_array.shape) == 0:
    print("correct")





correct


Need to complie results!!!! 

add to dataframe all of the precision and recallls 
plot the results and check for 
params don't have to be the best 


make a sepereate dataframe 

look: pd.concat

mention the params 

or have a collumn that has run number 

PRECISION: #test at ground truth / # test  

RECALL: # gt recovered / number ground truth 
(would be 100% if you found all the correct endponts...NO EXTRAS)